version: '3.8'
services:
  # Database - Mongo DB
  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./seed:/app
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./mongod.conf:/etc/mongod.conf
    env_file:
      - ../.env
    command: ["mongod", "--config", "/etc/mongod.conf"]